In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [2]:
dataset= np.genfromtxt('GD_BostonDatasetTraining.csv',delimiter=',')
x_test = np.genfromtxt('GD_BostonDatasetTest.csv',delimiter = ',')

In [3]:
dataset

array([[-0.40784991, -0.48772236, -1.2660231 , ...,  0.41057102,
        -1.09799011, 37.9       ],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.29116915,
        -0.52047412, 21.4       ],
       [ 0.1251786 , -0.48772236,  1.01599907, ..., -3.79579542,
         0.89107588, 12.7       ],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.33206621,
        -0.33404299, 20.8       ],
       [-0.41061997, -0.48772236, -1.15221381, ...,  0.203235  ,
        -0.74475218, 22.6       ],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.38787479,
        -1.35871335, 50.        ]])

In [4]:
y_train = dataset[:,-1] #last column
y_train

array([37.9, 21.4, 12.7, 19.9, 22.5, 32.7, 23.2, 21.5, 20.5, 33.3, 23.1,
       20. , 50. , 25. , 20.2, 16.4, 22.4, 20.4, 18.4, 37.3, 23.1, 34.7,
       33.1, 28.7, 15.6, 18.2, 17.2, 31.5, 26.6, 24.1, 22.3, 19.5, 36.1,
       17.6, 33.4,  8.8,  9.7, 13.4, 39.8, 24.4, 17.8, 24.3, 24. , 23.1,
       13.1, 16.7, 22.8, 27.5, 14.6, 13.4, 11. , 19.4, 15. , 44.8, 29.6,
       12.3, 24.6, 10.9, 28. , 30.8, 15.4, 18. , 35.2, 11.5, 19.5, 24.8,
       22.2, 20.1, 15.2, 50. , 17.1, 23. , 12. , 22. , 20. , 20.3, 17.2,
       37.2,  5. , 24.5, 18.9, 24.5, 24.8, 21.6,  7. , 17.7, 12.8, 14.9,
       18.3, 15.6, 19.9, 22.2, 16.7, 32.5, 25.1, 30.1, 16.1, 20.7, 46. ,
       22.3, 23. , 11.9, 23.3, 23.2, 22. , 10.5, 17.2, 29.8, 29. , 17.3,
       20.6, 20.1, 20.6, 17.8, 25. , 22.6, 18.7, 11.3,  9.6, 17.8, 23.9,
       38.7, 21.2, 25. , 28.5, 24. , 20.6,  5. , 22.9, 18.4, 31. , 36. ,
       20.8, 13.3, 23.2, 28.2, 43.8, 26.6, 23.9, 23.9, 27.9, 19.1, 30.5,
        8.3,  8.5, 16.5, 23.8, 19.6, 22.2, 24.3, 32

In [5]:
x_train = np.delete(dataset,-1,1)
x_train

array([[-0.40784991, -0.48772236, -1.2660231 , ..., -0.30309415,
         0.41057102, -1.09799011],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.29116915, -0.52047412],
       [ 0.1251786 , -0.48772236,  1.01599907, ...,  0.80657583,
        -3.79579542,  0.89107588],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.33206621, -0.33404299],
       [-0.41061997, -0.48772236, -1.15221381, ..., -0.71922039,
         0.203235  , -0.74475218],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.80657583,
         0.38787479, -1.35871335]])

In [6]:
size = x_train.shape
m = size[0]
n = size[1]
li = []
for j in range(n):
    for i in range(m):
        li.append([x_train[i,j]**2])
    x_train = np.append(x_train,np.array(li),axis = 1)
    li = []
    
for j in range(n):
    for i in range(m):
        li.append([x_train[i,j]**3])
    x_train = np.append(x_train,np.array(li),axis = 1)
    li = []
    
li = []
for j in range(n):
    for i in range(m):
        index = j+1
        if index == n:
            index = 0
        li.append([x_train[i,j]*x_train[i,index]])
    x_train = np.append(x_train,np.array(li),axis = 1)
    li = []

In [7]:
x_train.shape

(379, 52)

In [8]:
size = x_test.shape
m = size[0]
n = size[1]
li = []
for j in range(n):
    for i in range(m):
        li.append([x_test[i,j]**2])
    x_test = np.append(x_test,np.array(li),axis = 1)
    li = []
    
for j in range(n):
    for i in range(m):
        li.append([x_test[i,j]**3])
    x_test = np.append(x_test,np.array(li),axis = 1)
    li = []

li = []
for j in range(n):
    for i in range(m):
        index = j+1
        if index == n:
            index = 0
        li.append([x_test[i,j]*x_test[i,index]])
    x_test = np.append(x_test,np.array(li),axis = 1)
    li = []

In [9]:
x_test.shape

(127, 52)

In [10]:
scaler = preprocessing.StandardScaler()
scaler.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [11]:
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [12]:
size=x_train.shape
M=size[0]
N=size[1]
c=[1]*M
x_train=np.insert(x_train,N,c,axis=1)
print(x_train.shape)

(379, 53)


In [13]:
x_train.shape

(379, 53)

In [14]:
size=x_test.shape
M=size[0]
N=size[1]
c=[1]*M
x_test=np.insert(x_test,N,c,axis=1)
print(x_test.shape)

(127, 53)


In [15]:
x_test.shape

(127, 53)

In [16]:
x_train

array([[-0.40098068, -0.49042688, -1.28149216, ..., -0.03410629,
        -0.0065318 ,  1.        ],
       [-0.40053396, -0.49042688,  0.20753471, ...,  0.18439428,
        -0.16092832,  1.        ],
       [ 0.09900799, -0.49042688,  0.96425328, ..., -2.17455116,
        -0.22672629,  1.        ],
       ...,
       [-0.40141319, -0.49042688,  0.20753471, ...,  0.21405391,
        -0.21045435,  1.        ],
       [-0.40357903, -0.49042688, -1.16949207, ...,  0.18453031,
        -0.09951835,  1.        ],
       [ 0.30324229, -0.49042688,  0.96425328, ..., -0.0897489 ,
        -0.60485285,  1.        ]])

In [17]:
x_train.mean()

0.0188679245283019

In [18]:
x_test

array([[ 2.71887193, -0.49042688,  0.96425328, ..., -0.91929368,
         1.68954557,  1.        ],
       [-0.39679863, -0.49042688,  0.36404766, ...,  0.00691096,
        -0.06342537,  1.        ],
       [-0.4059786 , -0.49042688,  0.07830384, ...,  0.13375534,
        -0.16425954,  1.        ],
       ...,
       [-0.40301108,  2.08605624, -1.39205635, ...,  0.1004636 ,
        -0.116749  ,  1.        ],
       [-0.39659658, -0.49042688, -0.405594  , ...,  0.34505749,
        -0.35294234,  1.        ],
       [-0.14369589, -0.49042688,  1.17676627, ..., -0.75379386,
        -0.34251425,  1.        ]])

In [19]:
x_test.mean()

-0.03682975700379309

In [20]:
def run():
    lr = 0.018
    num_itr = 4000
    m = gd(lr,num_itr)
    print(m)
    return (m)

In [21]:
def gd(lr,num_itr):
    size = x_train.shape
    M = size[0]
    N = size[1]
    m = np.zeros(N)
    for i in range(num_itr):
        m = step_gradient(lr,m)
        print(i,cost(m))
    return m

In [22]:
def step_gradient(lr,m):
    size = x_train.shape
    M = size[0]
    N = size[1]
    m_slope = np.zeros(N)
    for i in range(M):
        y = y_train[i]
        x = x_train[i]
        for j in range(N):
            m_slope[j] += (-2/M) * (y - ((m*x).sum())) * x[j]
    for i in range(N):
        m[i] = m[i] - lr*m_slope[i]
    return m

In [23]:
def cost(m):
    size = x_train.shape
    M = size[0]
    N = size[1]
    cost = 0
    for i in range(M):
        y = y_train[i]
        x = x_train[i]
        cost += (1/M) * (y - (m*x).sum())**2
    return cost

In [24]:
def predict(x,m):
    size = len(x)
    y_pred = np.zeros(size)
    for i in range(size):
        y_pred[i]= (m*x[i]).sum()
    return y_pred

In [25]:
m = run()

0 537.7612603209425
1 493.0608319720536
2 455.5897532820284
3 422.3176353454388
4 392.1287666813987
5 364.5024737138227
6 339.12047366720753
7 315.746625523933
8 294.1874981971908
9 274.27749927782315
10 255.8719051713513
11 238.8427547547283
12 223.07600520382638
13 208.4693840901649
14 194.93069808648144
15 182.37647179674335
16 170.73083674282057
17 159.92461427479282
18 149.89455077163058
19 140.58267356935656
20 131.93574340227767
21 123.90478464293938
22 116.44467879187584
23 109.51380984304188
24 103.07375258117814
25 97.08899673483538
26 91.52670134902817
27 86.35647485655775
28 81.55017719394417
29 77.08174098495033
30 72.92700934604221
31 69.06358828742349
32 65.47071201607464
33 62.12911971302726
34 59.02094257085133
35 56.129600050450286
36 53.43970445753793
37 50.93697305538163
38 48.60814702676309
39 46.44091667867886
40 44.42385235123364
41 42.546340549909885
42 40.79852486986834
43 39.171251323639076
44 37.65601772070664
45 36.24492678002004
46 34.93064268512048
47 33.7

366 14.31888701574062
367 14.316124361016884
368 14.313373497102242
369 14.310634339890154
370 14.307906806178657
371 14.305190813657498
372 14.302486280895822
373 14.299793127329695
374 14.29711127325015
375 14.29444063979121
376 14.291781148918213
377 14.289132723416301
378 14.286495286879088
379 14.283868763697527
380 14.281253079048929
381 14.27864815888621
382 14.276053929927247
383 14.27347031964448
384 14.270897256254623
385 14.268334668708505
386 14.265782486681235
387 14.263240640562376
388 14.260709061446192
389 14.258187681122404
390 14.255676432066691
391 14.25317524743156
392 14.250684061037362
393 14.248202807363283
394 14.245731421538816
395 14.243269839334857
396 14.240817997155547
397 14.238375832029645
398 14.235943281602516
399 14.23352028412801
400 14.231106778460441
401 14.228702704046777
402 14.226308000919001
403 14.223922609686468
404 14.221546471528418
405 14.219179528186679
406 14.216821721958322
407 14.214472995688705
408 14.212133292764262
409 14.20980255710

725 13.7494278983658
726 13.748518436949746
727 13.747611168579931
728 13.746706085803696
729 13.745803181202161
730 13.744902447390082
731 13.744003877015622
732 13.743107462760143
733 13.742213197338083
734 13.741321073496662
735 13.74043108401578
736 13.739543221707743
737 13.738657479417173
738 13.737773850020751
739 13.736892326426986
740 13.73601290157618
741 13.735135568440104
742 13.734260320021889
743 13.733387149355794
744 13.732516049507119
745 13.7316470135719
746 13.730780034676824
747 13.729915105979034
748 13.729052220665944
749 13.728191371955065
750 13.727332553093833
751 13.726475757359474
752 13.725620978058773
753 13.724768208527937
754 13.72391744213245
755 13.72306867226689
756 13.722221892354733
757 13.721377095848222
758 13.720534276228218
759 13.719693427004039
760 13.718854541713238
761 13.718017613921516
762 13.717182637222512
763 13.716349605237733
764 13.715518511616274
765 13.71468935003473
766 13.713862114197076
767 13.71303679783448
768 13.71221339470511

1081 13.524462713326786
1082 13.524028978819835
1083 13.523596028190424
1084 13.523163859480128
1085 13.522732470736706
1086 13.522301860014087
1087 13.521872025372357
1088 13.521442964877608
1089 13.521014676602118
1090 13.520587158624167
1091 13.520160409028062
1092 13.519734425904158
1093 13.519309207348774
1094 13.518884751464164
1095 13.518461056358587
1096 13.518038120146146
1097 13.5176159409469
1098 13.517194516886708
1099 13.516773846097356
1100 13.516353926716388
1101 13.51593475688718
1102 13.515516334758875
1103 13.51509865848638
1104 13.514681726230345
1105 13.514265536157112
1106 13.513850086438739
1107 13.513435375252907
1108 13.513021400782975
1109 13.512608161217917
1110 13.512195654752361
1111 13.511783879586396
1112 13.51137283392579
1113 13.51096251598179
1114 13.510552923971161
1115 13.510144056116163
1116 13.509735910644586
1117 13.509328485789547
1118 13.508921779789764
1119 13.50851579088921
1120 13.508110517337341
1121 13.507705957388943
1122 13.50730210930421


1425 13.411127739037774
1426 13.410879166337853
1427 13.410630952859664
1428 13.410383097859583
1429 13.410135600595842
1430 13.40988846032856
1431 13.409641676319715
1432 13.40939524783319
1433 13.409149174134713
1434 13.408903454491853
1435 13.408658088174034
1436 13.408413074452552
1437 13.40816841260051
1438 13.407924101892872
1439 13.407680141606395
1440 13.407436531019712
1441 13.407193269413213
1442 13.406950356069144
1443 13.40670779027156
1444 13.406465571306276
1445 13.406223698460929
1446 13.405982171024961
1447 13.405740988289574
1448 13.405500149547775
1449 13.4052596540943
1450 13.405019501225711
1451 13.404779690240284
1452 13.404540220438099
1453 13.404301091120955
1454 13.404062301592402
1455 13.403823851157744
1456 13.40358573912403
1457 13.403347964800014
1458 13.403110527496214
1459 13.40287342652483
1460 13.402636661199784
1461 13.402400230836765
1462 13.402164134753097
1463 13.401928372267852
1464 13.401692942701752
1465 13.401457845377271
1466 13.40122307961853
1

1770 13.342546637618318
1771 13.342387997675072
1772 13.342229542719533
1773 13.342071272421187
1774 13.341913186450233
1775 13.341755284477609
1776 13.341597566175013
1777 13.341440031214763
1778 13.341282679269998
1779 13.341125510014502
1780 13.340968523122768
1781 13.340811718270054
1782 13.34065509513226
1783 13.340498653386044
1784 13.340342392708749
1785 13.340186312778414
1786 13.340030413273807
1787 13.339874693874329
1788 13.339719154260166
1789 13.339563794112122
1790 13.33940861311175
1791 13.339253610941265
1792 13.339098787283593
1793 13.3389441418223
1794 13.338789674241724
1795 13.338635384226802
1796 13.338481271463195
1797 13.33832733563725
1798 13.338173576435974
1799 13.338019993547078
1800 13.337866586658933
1801 13.33771335546056
1802 13.337560299641714
1803 13.337407418892765
1804 13.337254712904759
1805 13.337102181369449
1806 13.336949823979227
1807 13.336797640427132
1808 13.336645630406897
1809 13.336493793612911
1810 13.336342129740208
1811 13.33619063848447

2114 13.29701781337005
2115 13.2969072898957
2116 13.296796870460142
2117 13.296686554900829
2118 13.29657634305551
2119 13.296466234762226
2120 13.29635622985934
2121 13.296246328185573
2122 13.296136529579867
2123 13.296026833881598
2124 13.295917240930354
2125 13.295807750566055
2126 13.295698362628988
2127 13.295589076959681
2128 13.295479893399001
2129 13.295370811788123
2130 13.295261831968526
2131 13.295152953782
2132 13.295044177070647
2133 13.294935501676854
2134 13.294826927443324
2135 13.29471845421306
2136 13.294610081829418
2137 13.294501810135934
2138 13.29439363897662
2139 13.294285568195615
2140 13.29417759763749
2141 13.294069727147054
2142 13.293961956569404
2143 13.293854285749987
2144 13.293746714534493
2145 13.293639242768965
2146 13.293531870299711
2147 13.293424596973317
2148 13.293317422636685
2149 13.29321034713705
2150 13.293103370321862
2151 13.292996492038942
2152 13.292889712136363
2153 13.29278303046246
2154 13.292676446865933
2155 13.292569961195749
2156 

2459 13.264116662888881
2460 13.264034179042364
2461 13.263951757953269
2462 13.263869399535706
2463 13.263787103703878
2464 13.263704870372207
2465 13.263622699455217
2466 13.263540590867597
2467 13.2634585445242
2468 13.263376560339989
2469 13.263294638230127
2470 13.26321277810988
2471 13.26313097989471
2472 13.263049243500179
2473 13.26296756884201
2474 13.2628859558361
2475 13.26280440439845
2476 13.262722914445279
2477 13.262641485892848
2478 13.262560118657662
2479 13.26247881265632
2480 13.26239756780556
2481 13.262316384022316
2482 13.262235261223614
2483 13.26215419932665
2484 13.26207319824877
2485 13.261992257907448
2486 13.261911378220278
2487 13.261830559105078
2488 13.261749800479745
2489 13.261669102262315
2490 13.261588464371
2491 13.261507886724145
2492 13.261427369240206
2493 13.261346911837823
2494 13.26126651443576
2495 13.261186176952936
2496 13.26110589930838
2497 13.261025681421286
2498 13.260945523210996
2499 13.260865424596949
2500 13.260785385498796
2501 13.2

2804 13.23887763355283
2805 13.238812572498295
2806 13.238747551776385
2807 13.238682571338945
2808 13.238617631137885
2809 13.238552731125157
2810 13.238487871252833
2811 13.238423051473045
2812 13.238358271737974
2813 13.238293531999913
2814 13.23822883221124
2815 13.238164172324382
2816 13.238099552291828
2817 13.238034972066169
2818 13.237970431600083
2819 13.237905930846308
2820 13.237841469757639
2821 13.23777704828698
2822 13.237712666387273
2823 13.237648324011579
2824 13.237584021112996
2825 13.237519757644714
2826 13.237455533559997
2827 13.237391348812183
2828 13.237327203354672
2829 13.23726309714095
2830 13.237199030124586
2831 13.237135002259196
2832 13.237071013498522
2833 13.237007063796305
2834 13.23694315310641
2835 13.236879281382752
2836 13.236815448579335
2837 13.236751654650252
2838 13.236687899549631
2839 13.23662418323169
2840 13.23656050565071
2841 13.236496866761057
2842 13.236433266517182
2843 13.236369704873589
2844 13.236306181784867
2845 13.236242697205624

3148 13.218591253923888
3149 13.218537671352195
3150 13.218484116270178
3151 13.218430588649435
3152 13.21837708846155
3153 13.218323615678143
3154 13.218270170270928
3155 13.218216752211605
3156 13.218163361471934
3157 13.218109998023719
3158 13.218056661838807
3159 13.218003352889085
3160 13.217950071146497
3161 13.217896816582982
3162 13.217843589170558
3163 13.217790388881271
3164 13.217737215687205
3165 13.217684069560523
3166 13.21763095047337
3167 13.217577858397961
3168 13.217524793306538
3169 13.217471755171431
3170 13.217418743964945
3171 13.21736575965945
3172 13.217312802227383
3173 13.217259871641168
3174 13.217206967873338
3175 13.217154090896392
3176 13.217101240682917
3177 13.217048417205522
3178 13.216995620436888
3179 13.216942850349657
3180 13.216890106916624
3181 13.216837390110532
3182 13.216784699904187
3183 13.216732036270434
3184 13.216679399182194
3185 13.21662678861239
3186 13.216574204533973
3187 13.216521646919967
3188 13.216469115743429
3189 13.216416610977

3493 13.20156512541824
3494 13.201519584771157
3495 13.201474063855882
3496 13.201428562654897
3497 13.201383081150684
3498 13.20133761932575
3499 13.201292177162633
3500 13.201246754643885
3501 13.201201351752113
3502 13.201155968469905
3503 13.201110604779897
3504 13.20106526066475
3505 13.20101993610714
3506 13.200974631089762
3507 13.200929345595325
3508 13.200884079606595
3509 13.200838833106335
3510 13.200793606077333
3511 13.200748398502402
3512 13.200703210364399
3513 13.200658041646163
3514 13.200612892330591
3515 13.200567762400585
3516 13.200522651839067
3517 13.200477560629018
3518 13.20043248875338
3519 13.20038743619514
3520 13.20034240293736
3521 13.200297388963067
3522 13.20025239425532
3523 13.200207418797197
3524 13.200162462571843
3525 13.200117525562343
3526 13.20007260775191
3527 13.200027709123656
3528 13.199982829660836
3529 13.199937969346635
3530 13.199893128164327
3531 13.199848306097156
3532 13.199803503128429
3533 13.199758719241427
3534 13.19971395441954
35

3837 13.186957454665128
3838 13.186917806115195
3839 13.186878172432136
3840 13.186838553604662
3841 13.18679894962149
3842 13.186759360471397
3843 13.18671978614308
3844 13.186680226625356
3845 13.18664068190699
3846 13.186601151976754
3847 13.186561636823482
3848 13.186522136435991
3849 13.186482650803118
3850 13.186443179913681
3851 13.186403723756607
3852 13.186364282320717
3853 13.18632485559491
3854 13.186285443568096
3855 13.186246046229192
3856 13.186206663567122
3857 13.186167295570836
3858 13.18612794222929
3859 13.186088603531466
3860 13.186049279466308
3861 13.186009970022848
3862 13.18597067519009
3863 13.185931394957064
3864 13.185892129312775
3865 13.185852878246322
3866 13.185813641746716
3867 13.185774419803062
3868 13.18573521240445
3869 13.185696019539993
3870 13.185656841198767
3871 13.185617677369944
3872 13.185578528042653
3873 13.185539393206026
3874 13.18550027284927
3875 13.185461166961531
3876 13.185422075532028
3877 13.185382998549962
3878 13.185343936004546


In [27]:
m

array([-1.07586263,  0.03998034,  0.17034454,  0.30085958, -3.44918292,
        1.59367351, -0.53414819, -3.28709404,  1.75477364,  0.7758161 ,
       -0.15911024, -0.3283021 , -5.53961658,  2.18308828, -0.10076082,
        0.31739116,  0.30085958, -1.87929523,  1.18676197,  1.11269905,
        3.36399464, -2.2656473 ,  0.2002151 ,  0.41787254, -1.94129864,
        1.491031  , -0.83699664,  0.50792371,  0.03630734,  0.30085958,
        2.1997822 ,  0.36169572,  0.61341308, -1.6393351 ,  1.63934296,
       -3.17967179, -0.57773854, -0.44135565, -0.18155255,  1.33305747,
       -0.25576983,  1.5580635 , -1.60524677, -1.04403131, -0.19838031,
        1.49181134, -0.90363375,  0.63776499,  1.57741376,  0.11343694,
       -1.13170822, -1.1654259 , 22.60949868])

In [28]:
y_pred = predict(x_train,m)
y_pred

array([36.20697575, 23.02966082, 10.72946931, 16.75727442, 19.61115612,
       32.44595525, 20.86504907, 17.77206326, 23.02061143, 39.71208051,
       24.66874384, 20.20147981, 48.82533249, 23.29616728, 19.22011904,
       15.6664682 , 22.45139563, 19.65165193, 18.17171938, 32.66576161,
       22.66271177, 32.28826268, 34.76340917, 28.04987854, 13.21877295,
       18.67709488, 18.48223418, 33.59120357, 31.13150162, 24.54110314,
       23.38686494, 15.82522096, 33.51171601, 18.90948592, 35.01963596,
        4.30976519, 12.55591483, 12.58096087, 37.22668201, 21.22816435,
       14.20353663, 28.99850068, 23.44961697, 22.99529991, 13.51357992,
       17.70281317, 24.4337257 , 24.80764941, 14.72394647, 10.72218756,
       14.68915367, 19.06845558, 19.62403358, 43.24872933, 28.60007709,
       14.53802798, 27.31440595, 14.73448943, 27.5725607 , 29.07169485,
       15.30757983, 19.14865658, 36.75310679, 15.76260312, 17.16568448,
       26.9715839 , 18.08178762, 15.19755422, 12.88900878, 51.11

In [29]:
def score(y_pred,y_truth):
    u = ((y_truth - y_pred)**2).sum()
    v = ((y_truth - y_truth.mean())**2).sum()
    return 1-(u/v)

In [30]:
score(y_pred,y_train)

0.8501046821622757

In [34]:
ypred2 = predict(x_test,m)
ypred2

array([15.63325967, 29.10366487, 19.18146188, 23.79185001, 21.42664239,
       12.81233793, 28.39145405, 23.76666798, 17.33726593, 23.25191182,
       25.24336117, 15.9195531 , 19.51361948, 19.17415052, 50.44726935,
       20.7096096 , 23.56500765, 24.84078633, 15.60868027, 29.86064625,
       21.51446169, 22.15179125, 32.19692034, 36.03582159, 31.50554779,
       18.10454463, 21.20202469, 30.66828792, 25.09426866, 29.02223689,
       14.94803168, 27.65802688, 19.57211957, 23.59602524, 11.388694  ,
       27.29020292, 24.04607365, 19.90272226, 23.97592481, 10.35986875,
       17.09266431, 25.92605523, 27.44629813, 20.48591867, 17.83529589,
       12.82984554, 47.46522042, 22.58437271, 33.52707684, 12.93973625,
       16.67707925, 46.74877359, 13.73889527, 21.80267969, 14.46929833,
       21.25614998, 15.1609975 , 23.23573965, 13.81428325, 14.02668969,
       10.73568341, 27.75763579, 20.79623244, 25.94892249, 17.19704938,
       16.95432404, 33.78102581, 14.92732668, 28.03372043, 21.38

In [35]:
np.savetxt('FinalPredictions_GD_BostonDataset.csv', ypred2,fmt='%f')