In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [2]:
dataset= np.genfromtxt('CombinedCyclePowerPlant_Training.csv',delimiter=',')
x_test = np.genfromtxt('CombinedCyclePowerPlant_Test.csv',delimiter = ',')

In [3]:
dataset

array([[   8.58,   38.38, 1021.03,   84.37,  482.26],
       [  21.79,   58.2 , 1017.21,   66.74,  446.94],
       [  16.64,   48.92, 1011.55,   78.76,  452.56],
       ...,
       [  29.8 ,   69.34, 1009.36,   64.74,  437.65],
       [  16.37,   54.3 , 1017.94,   63.63,  459.97],
       [  30.11,   62.04, 1010.69,   47.96,  444.42]])

In [4]:
y_train = dataset[:,-1] #last column
y_train

array([482.26, 446.94, 452.56, ..., 437.65, 459.97, 444.42])

In [5]:
x_train = np.delete(dataset,-1,1)
x_train

array([[   8.58,   38.38, 1021.03,   84.37],
       [  21.79,   58.2 , 1017.21,   66.74],
       [  16.64,   48.92, 1011.55,   78.76],
       ...,
       [  29.8 ,   69.34, 1009.36,   64.74],
       [  16.37,   54.3 , 1017.94,   63.63],
       [  30.11,   62.04, 1010.69,   47.96]])

In [6]:
size = x_train.shape
m = size[0]
n = size[1]
li = []
for j in range(n):
    for i in range(m):
        li.append([x_train[i,j]**2])
    x_train = np.append(x_train,np.array(li),axis = 1)
    li = []
    
li = []
for j in range(n):
    for i in range(m):
        index = j+1
        if index == n:
            index = 0
        li.append([x_train[i,j]*x_train[i,index]])
    x_train = np.append(x_train,np.array(li),axis = 1)
    li = []

In [7]:
x_train.shape

(7176, 12)

In [8]:
size = x_test.shape
m = size[0]
n = size[1]
li = []
for j in range(n):
    for i in range(m):
        li.append([x_test[i,j]**2])
    x_test = np.append(x_test,np.array(li),axis = 1)
    li = []

li = []
for j in range(n):
    for i in range(m):
        index = j+1
        if index == n:
            index = 0
        li.append([x_test[i,j]*x_test[i,index]])
    x_test = np.append(x_test,np.array(li),axis = 1)
    li = []

In [9]:
x_test.shape

(2392, 12)

In [10]:
scaler = preprocessing.StandardScaler()
scaler.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [11]:
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [12]:
size=x_train.shape
M=size[0]
N=size[1]
c=[1]*M
x_train=np.insert(x_train,N,c,axis=1)
print(x_train.shape)

(7176, 13)


In [13]:
x_train.shape

(7176, 13)

In [14]:
size=x_test.shape
M=size[0]
N=size[1]
c=[1]*M
x_test=np.insert(x_test,N,c,axis=1)
print(x_test.shape)

(2392, 13)


In [15]:
x_test.shape

(2392, 13)

In [16]:
x_train

array([[-1.47827466e+00, -1.24764165e+00,  1.30221067e+00, ...,
         8.00076438e-01, -1.38392842e+00,  1.00000000e+00],
       [ 2.89012041e-01,  3.06797549e-01,  6.61749044e-01, ...,
        -4.28576655e-01,  1.59529799e-01,  1.00000000e+00],
       [-3.99975582e-01, -4.21012529e-01, -2.87207194e-01, ...,
         3.64318663e-01, -1.44141172e-01,  1.00000000e+00],
       ...,
       [ 1.36062192e+00,  1.18048335e+00, -6.54382840e-01, ...,
        -5.99701729e-01,  1.16329940e+00,  1.00000000e+00],
       [-4.36097263e-01,  9.29089763e-04,  7.84140927e-01, ...,
        -6.38363211e-01, -7.12487004e-01,  1.00000000e+00],
       [ 1.40209496e+00,  6.07960340e-01, -4.31394890e-01, ...,
        -1.73531383e+00,  1.37997842e-01,  1.00000000e+00]])

In [17]:
x_train.mean()

0.07692307692307265

In [18]:
x_test

array([[-1.02742256, -0.96138014,  0.72378329, ...,  1.22701235,
        -0.61842094,  1.        ],
       [-1.01136848, -1.25783726, -0.09942787, ...,  0.56790539,
        -0.83080161,  1.        ],
       [ 0.97398614,  1.62360048, -1.27807846, ...,  0.34788134,
         1.57770833,  1.        ],
       ...,
       [ 0.62748557,  0.93814142, -0.69965107, ...,  1.24299222,
         1.80892592,  1.        ],
       [ 0.51644485, -0.90099073,  0.11685368, ..., -0.54076088,
         0.32830979,  1.        ],
       [ 0.28499852,  0.46914312,  0.95515424, ...,  0.83564149,
         0.99773346,  1.        ]])

In [19]:
x_test.mean()

0.08322008002358758

In [20]:
def run():
    lr = 0.1
    num_itr = 2000
    m = gd(lr,num_itr)
    print(m)
    return (m)

In [21]:
def gd(lr,num_itr):
    size = x_train.shape
    M = size[0]
    N = size[1]
    m = np.zeros(N)
    for i in range(num_itr):
        m = step_gradient(lr,m)
        print(i,cost(m))
    return m

In [22]:
def step_gradient(lr,m):
    size = x_train.shape
    M = size[0]
    N = size[1]
    m_slope = np.zeros(N)
    for i in range(M):
        y = y_train[i]
        x = x_train[i]
        for j in range(N):
            m_slope[j] += (-2/M) * (y - ((m*x).sum())) * x[j]
    for i in range(N):
        m[i] = m[i] - lr*m_slope[i]
    return m

In [23]:
def cost(m):
    size = x_train.shape
    M = size[0]
    N = size[1]
    cost = 0
    for i in range(M):
        y = y_train[i]
        x = x_train[i]
        cost += (1/M) * (y - (m*x).sum())**2
    return cost

In [24]:
def predict(x,m):
    size = len(x)
    y_pred = np.zeros(size)
    for i in range(size):
        y_pred[i]= (m*x[i]).sum()
    return y_pred

In [25]:
m = run()

0 132262.50346131533
1 84632.22939131784
2 54167.657599688224
3 34674.96372656553
4 22200.68091563557
5 14217.281956461295
6 9107.833619520277
7 5837.6716009584225
8 3744.6534550954025
9 2405.0175898316998
10 1547.5578164582337
11 998.7013982610396
12 647.360618255092
13 422.4381878851437
14 278.4308017705168
15 186.21542539442524
16 127.15251160133184
17 89.31204714492222
18 65.05821032739881
19 49.50354070747676
20 39.5195977372218
21 33.1037734970115
22 28.974045140522808
23 26.309609726843767
24 24.58488463991835
25 23.46326273856958
26 22.729111194297897
27 22.244246865586963
28 21.9200771580627
29 21.69976723337171
30 21.546824462467864
31 21.437790247212153
32 21.357560846588346
33 21.296391017316814
34 21.247974874520466
35 21.20821636367421
36 21.174441249518214
37 21.144891820069265
38 21.118402653823505
39 21.09419237664137
40 21.07172974709819
41 21.050647394791625
42 21.030686128540964
43 21.01165887198444
44 20.993427215244033
45 20.975886088337983
46 20.958953673818268
4

368 19.36461297445972
369 19.362578211212806
370 19.360551305999277
371 19.358532226281334
372 19.356520939669807
373 19.3545174139233
374 19.35252161694657
375 19.35053351679046
376 19.348553081650632
377 19.34658027986575
378 19.34461507991767
379 19.342657450430476
380 19.340707360168203
381 19.33876477803576
382 19.33682967307669
383 19.334902014472952
384 19.33298177154372
385 19.331068913744737
386 19.329163410667448
387 19.32726523203815
388 19.32537434771713
389 19.32349072769776
390 19.321614342105796
391 19.319745161198725
392 19.317883155364758
393 19.316028295122262
394 19.31418055111885
395 19.31233989413044
396 19.310506295061057
397 19.308679724941747
398 19.3068601549298
399 19.305047556307947
400 19.303241900484295
401 19.301443158990725
402 19.299651303482804
403 19.297866305739078
404 19.296088137660053
405 19.294316771267756
406 19.292552178705087
407 19.290794332235112
408 19.289043204240357
409 19.28729876722243
410 19.285560993800992
411 19.283829856713552
412 19

731 18.96018217364502
732 18.959640101175275
733 18.959099843686204
734 18.95856139401792
735 18.958024745039815
736 18.957489889650166
737 18.956956820776536
738 18.9564255313755
739 18.95589601443222
740 18.955368262960764
741 18.954842270003557
742 18.954318028631675
743 18.953795531944564
744 18.95327477306967
745 18.952755745162715
746 18.952238441407268
747 18.951722855015237
748 18.951208979225456
749 18.950696807305114
750 18.950186332548718
751 18.949677548278164
752 18.949170447842718
753 18.948665024618702
754 18.948161272009614
755 18.94765918344591
756 18.947158752385075
757 18.94665997231103
758 18.94616283673449
759 18.945667339192784
760 18.945173473249508
761 18.94468123249453
762 18.944190610544098
763 18.943701601040498
764 18.943214197652043
765 18.94272839407264
766 18.942244184022336
767 18.94176156124681
768 18.941280519516727
769 18.940801052629098
770 18.940323154405622
771 18.939846818693518
772 18.939372039365058
773 18.938898810317607
774 18.938427125473392


1090 18.84272849318536
1091 18.84253893474203
1092 18.842349839334485
1093 18.842161205296964
1094 18.841973030970347
1095 18.841785314701784
1096 18.841598054845516
1097 18.841411249762167
1098 18.84122489781907
1099 18.841038997389777
1100 18.840853546854515
1101 18.840668544599975
1102 18.840483989019393
1103 18.840299878512198
1104 18.840116211484446
1105 18.83993298634845
1106 18.83975020152266
1107 18.83956785543231
1108 18.83938594650858
1109 18.83920447318906
1110 18.839023433917493
1111 18.838842827143853
1112 18.838662651324253
1113 18.838482904920934
1114 18.83830358640262
1115 18.838124694243643
1116 18.83794622692491
1117 18.837768182932983
1118 18.83759056076071
1119 18.837413358906797
1120 18.837236575876062
1121 18.83706021017902
1122 18.836884260332692
1123 18.836708724859395
1124 18.836533602287744
1125 18.836358891151892
1126 18.836184589992325
1127 18.8360106973547
1128 18.83583721179093
1129 18.83566413185856
1130 18.83549145612104
1131 18.835319183147117
1132 18.8

1437 18.796307347973265
1438 18.796211923892248
1439 18.796116647751354
1440 18.79602151912085
1441 18.79592653757268
1442 18.79583170268048
1443 18.79573701401943
1444 18.795642471166197
1445 18.795548073699308
1446 18.795453821198613
1447 18.79535971324568
1448 18.79526574942368
1449 18.795171929317046
1450 18.79507825251219
1451 18.794984718596847
1452 18.79489132716024
1453 18.794798077793182
1454 18.794704970088254
1455 18.794612003639298
1456 18.79451917804157
1457 18.794426492892036
1458 18.794333947789383
1459 18.794241542333367
1460 18.79414927612558
1461 18.794057148768662
1462 18.793965159867234
1463 18.793873309027155
1464 18.79378159585594
1465 18.793690019962202
1466 18.793598580956196
1467 18.793507278449884
1468 18.793416112056377
1469 18.793325081390233
1470 18.79323418606754
1471 18.793143425705882
1472 18.793052799924112
1473 18.792962308342737
1474 18.792871950583013
1475 18.792781726268736
1476 18.792691635024045
1477 18.792601676475126
1478 18.79251185024925
1479 

1784 18.76985484005842
1785 18.769793114176185
1786 18.769731451354858
1787 18.769669851468112
1788 18.76960831438964
1789 18.769546839994153
1790 18.769485428156276
1791 18.76942407875121
1792 18.76936279165441
1793 18.769301566742186
1794 18.769240403890663
1795 18.769179302976625
1796 18.769118263877285
1797 18.769057286470343
1798 18.768996370633506
1799 18.76893551624536
1800 18.7688747231845
1801 18.768813991330067
1802 18.768753320561586
1803 18.768692710758998
1804 18.768632161802536
1805 18.76857167357267
1806 18.768511245950798
1807 18.76845087881808
1808 18.768390572056337
1809 18.768330325547797
1810 18.76827013917498
1811 18.768210012820774
1812 18.768149946368357
1813 18.76808993970157
1814 18.768029992704278
1815 18.76797010526093
1816 18.767910277256416
1817 18.76785050857553
1818 18.767790799104002
1819 18.767731148727595
1820 18.76767155733247
1821 18.76761202480525
1822 18.767552551032804
1823 18.767493135902292
1824 18.76743377930154
1825 18.76737448111834
1826 18.7

In [26]:
m

array([-1.53102405e+01, -3.35061557e+00,  6.18970781e-01,  2.63982573e+00,
        3.75413878e+00,  1.66314567e+00, -1.02869120e-01, -3.98336316e+00,
        2.80319055e+00, -2.90401671e+00,  1.77236469e+00, -3.60978925e+00,
        4.54431293e+02])

In [27]:
y_pred = predict(x_train,m)
y_pred

array([480.71855552, 449.31265742, 459.61043743, ..., 433.56645796,
       460.54193946, 437.16545913])

In [28]:
def score(y_pred,y_truth):
    u = ((y_truth - y_pred)**2).sum()
    v = ((y_truth - y_truth.mean())**2).sum()
    return 1-(u/v)

In [29]:
score(y_pred,y_train)

0.9361005245710569

In [32]:
ypred2 = predict(x_test,m)
ypred2

array([470.71116225, 472.4527631 , 433.88932295, ..., 437.62670076,
       450.50104901, 446.10760408])

In [33]:
np.savetxt('FinalPredictions_GD_CombinedCyclePowerPlant.csv', ypred2,fmt='%f')